# Generated by Django 3.0 on 2022-06-21 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accounts',
            table=None,
        ),
        migrations.AlterModelTable(
            name='sales',
            table=None,
        ),
    ]
