# Generated by Django 3.0 on 2022-06-21 11:16

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('FinApp', '0003_sales_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='Country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
